CREATE TABLE
    DEMO.LINE_ITEM_BASE
(
    L_COMMENT VARCHAR,
    L_COMMITDATE DATE,
    L_DISCOUNT NUMBER,
    L_EXTENDEDPRICE NUMBER,
    L_LINENUMBER NUMBER,
    L_LINESTATUS VARCHAR,
    L_ORDERKEY NUMBER,
    L_PARTKEY NUMBER,
    L_QUANTITY NUMBER,
    L_RECEIPTDATE DATE,
    L_RETURNFLAG VARCHAR,
    L_SHIPDATE DATE,
    L_SHIPINSTRUCT VARCHAR,
    L_SHIPMODE VARCHAR,
    L_SUPPKEY NUMBER,
    L_TAX NUMBER
);
