CREATE OR REPLACE PROCEDURE
    DEMO.SP_TRANSFORM_LINE_ITEM()
RETURNS TEXT
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO FINAL_ORDERS
    SELECT
        L_ORDERKEY AS ORDERKEY,
        SUM(L_QUANTITY) AS TOTAL_QUANTITY,
        COUNT(*) AS TOTAL_NUMBER_OF_ITEMS,
        SUM(L_EXTENDEDPRICE) TOTAL_PRICE
    FROM DEMO.LINE_ITEM_BASE
    GROUP BY ALL;
END;
$$
;