name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install schemachange
        run: pip install schemachange

      - name: Run schemachange deployment
        run: |
          schemachange \
            -f scripts/ \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -r ${{ secrets.SNOWFLAKE_ROLE }} \
            -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            -d ${{ secrets.SNOWFLAKE_DATABASE }} \
            -s ${{ secrets.SNOWFLAKE_SCHEMA }} \
            -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --create-change-history-table
