name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Decode connections.toml
        run: |
          echo "${{ secrets.CONNECTIONS_TOML_B64 }}" | base64 -d > connections.toml

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run schemachange deployment
        run: |
          schemachange --config-file-name schemachange-config.yml
